### ISSUE TITLE
Enable access to HTTP server

### ISSUE THREAD

**Issue by rose-m** [igorzg/typeix#3]
The server created with `httpServer` is not available outside of the method. As such it is difficult to integrate additional modules like [`ws`](https://github.com/websockets/ws) which would need access to the created server.

Suggestion: Expose the server by returning an object instead of the array of modules from `httpServer`.

**Comment by igorzg** [comment]
@rose-m hey nobody stop you to do custom implementation of httpServer, access to http server is limited in order to not brake a request flow. https://github.com/igorzg/typeix/wiki

**Comment by rose-m** [comment]
I‘m already working on some WebSocket integration using proper Decorators and a comparable resolution system. Will probably take some more work but so far seems to work...

**Comment by igorzg** [comment]
@rose-m I'm looking forward to PR :)
